### ISSUE TITLE
viewDate only works the first time the widget displays

### ISSUE THREAD

**Issue by stefanor** [Eonasdan/bootstrap-datetimepicker#1959]
And calling `viewDate()` on `dp.show` (which you'd think would work as a workaround) has no effect. The only way I can do this is to call `date()` twice, once to change the page, once to unset the date.

https://jsfiddle.net/5gpsbu5r/

That fiddle has two datepickers, so you can open and close each one too see the change in behaviour on later displays.

**Comment by xerxes2** [comment]
I think I got a similar problem. The first time it displays it works fine but after that it switches from showing months to dates.

https://jsfiddle.net/4durenm8/

**Comment by Andrei83** [comment]
Same problem. viewMode or format: "MM/YYYY" works only for the first time.
In version 4.7.14 it works fine.

**Comment by vert3x** [comment]
I have the same problem. Does anyone knows how to fix this? :(

**Comment by vert3x** [comment]
I think I found a solution but I don't know if it will generate other issues or not.
I commented the line 950 that has `currentViewMode = 0;` after hiding the widget and it worked for me.
[jsfiddle](https://jsfiddle.net/vert3x/wxo8zmmz/)

**Comment by Andrei83** [comment]
Just download the latest version. Already fixed there.

**Comment by vert3x** [comment]
Sorry what version? I think the latest version is 4.17.45.

**Comment by vert3x** [comment]
I think you mean the version 4.17.46 in master branch which is not released.
Thank you I'll use it.

**Comment by junkystu** [comment]
I'm using 4.17.46 and I'm still having this issue. It doesn't look like it's fixed.

**Comment by Andrei83** [comment]
I'm using the latest version (4.17.46) and everything is ok.

**Comment by William-H-M** [comment]
This has been fixed on version 4.17.47 so I'll be closing this.

**Comment by junkystu** [comment]
This issue is still happening for me. Please see this [fiddle](https://jsfiddle.net/5gpsbu5r/3/).

Click the input and the view shown is for January 2015. Click outside the datetime picker to close it and then click the input - the shown view is now the current month (i.e. August 2017) instead of the `viewDate` which should be January.

**Comment by William-H-M** [comment]
Hi, seems like still appear and I confused it with the `viewMode` option that it's the one working.

**Comment by fmmich** [comment]
@junkystu, I had the same problem and found this issue report.  If you're able to capture your initial viewed date and the selected date from the dp.change event, adding the following dp.hide event worked for me (pardon my ES6).  This resets the viewDate after the datetimepicker is hidden:

```
$(this.ele).on('dp.hide', () => {
    if (!this.selectedDate && this.viewDate) {
        setTimeout(() => {
            $(this.ele).data('DateTimePicker').viewDate(this.viewDate);
        }, 0);
    }
});
```

**Comment by junkystu** [comment]
@fmmich thank you for the suggestion but unfortunately it does not work. The event gets triggered indeed and I'm able to grab the view date from the initial `date-view-date` on the picker/input however, setting the view date has the same effect: it defaults after being shown correctly once. Also, using a timeout throws an error for me:

```
Uncaught TypeError: Cannot read property 'append' of undefined at fillDate
```

**Comment by William-H-M** [comment]
Ok, I'll provide the current dirty fix as It seems a lot of people use this option:

```
$('#myDatepicker').on('dp.hide', function() {
  setTimeout(function() {
    $('#myDatepicker').data('DateTimePicker')
      .viewDate(moment('2015-01-01 00:00:00'));
  }, 1);
});
```
In my case @fmmich workaround (that is basically the same I'm doing with the difference he's using ES6, and probably that's why is not working for @junkystu )

**Comment by junkystu** [comment]
Thank you @William-H-M that worked indeed. I did translate the example by @fmmich from ES6 however, I was passing the `dateViewDate` attribute as a string rather than a moment object. Noticing your example, I've added the moment in and it works fine.
Thanks a lot for the dirty workaround, it will do for now :+1:
