### ISSUE TITLE
v4: fix events namespacing

### ISSUE THREAD

**Issue by mikk150** [Eonasdan/bootstrap-datetimepicker#751]
Please for once, fix event namespaces.
Currently events are back to front, so event name is always dp and namespace is "event type"
events should be <event name>.<namespace>
so for instance "dp.change" should really be "change.dp"
I understand that on V3 we shouldn't break things, but on V4 we have right to make things right

**Comment by Eonasdan** [comment]
this has already been done.

**Comment by mikk150** [comment]
so V4 public api is wrong?

**Comment by Eonasdan** [comment]
yes the wiki is wrong. I have updated docs to upload this week

**Comment by mikk150** [comment]
I still do not see it, even in code? now that it is live? so I think maybe reopen?

**Comment by seleckis** [comment]
+1
please fix documentation

**Comment by nikoskalogridis** [comment]
@Eonasdan, at this point we should not change the events namespacing as we have already gone in v4.0.0. Changing the events now would require major version upgrade (v5.x.x). 

I have noticed that myself when commiting at v.4.0.0-beta that the namespacing was incorrect hence the change to code. 

But I have noticed then that there was an issue with change.dp. I cannot recall what exactly the issue was (something had to do with change.dp firing and listeners for change event triggering).

May I suggest to further investigate this and discuss whether it worths breaking versioning rules at this point.

**Comment by Eonasdan** [comment]
@nikoskalogridis I do recall there being issues with Knockout and `change.dp`. We can roll back my change in dev.

**Comment by Eonasdan** [comment]
we' rolled back the changes in dev. We plan to have this (really) fixed in v5 as breaking change

**Comment by mikk150** [comment]
Yea, I agree, you cannot change such a big thing in it when it is live
